name: Update Stats
on:
  schedule:
    - cron: '0 18 * * *'  # Codziennie o 18:00
  push:
    branches: [ "main" ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update README
        run: |
          echo "### 🚀 Czas kodowania dziś: 2h" >> README.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update stats"
          git push
